version: "3.8"

volumes:
  build_folder: null

services:
  nginx:
    image: jaebin19/console-log:nginx
    build: ./nginx

  backend:
    image: jaebin19/console-log:backend
    build: ./backend

  frontend:
    image: jaebin19/console-log:frontend
    build: ./frontend