spring:
  profiles:
    active: local




#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  jwt:
    token:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length:
        access: 3600000
        refresh: 1210000000